---
- name: Clone a repo with separate git directory
  ansible.builtin.git:
    repo: "{{ lb1054_bootc_config_example_repo }}"
    dest: "{{ lb1054_bootc_config_example_repo_dest_path }}"

- name: Copy wordpress-quadlet directory
  ansible.builtin.copy:
    src: "{{ lb1054_bootc_config_example_repo_dest_path }}/examples/wordpress-quadlet/"
    dest: /home/lab-user/wordpress-quadlet/
    owner: lab-user
    group: lab-user
    mode: 0644

- name: Recursively remove repo directory
  ansible.builtin.file:
    path: "{{ lb1054_bootc_config_example_repo_dest_path }}"
    state: absent
