---

- name: Include host unsubscribe tasks
  when: lb1054_bootc_rhn_repository_unsubscribe | bool
  ansible.builtin.include_tasks:
    file: unsubscribe.yml

- name: Include host subscribe tasks
  when: lb1054_bootc_rhn_repository_subscribe | bool
  ansible.builtin.include_tasks:
    file: subscribe.yml
